exp_name: ???
run_name: null

save_path: /home/mila/l/lea.cote-turcotte/CDARL/representation/ILCM/logs
base_dir: /home/mila/l/lea.cote-turcotte/CDARL/representation/ILCM
exp_dir: /home/mila/l/lea.cote-turcotte/CDARL/data/causalcircuit
overwrite_existing: true

debug: false
verbose: true

seed: 1